### ISSUE TITLE
Spectrum data model classes.

### ISSUE THREAD

**Issue by ypriverol** [BigDataProteomics/bgp-core#2]
@ruiwanguk  We should start with the spectrum data model classes, every class will extend an interface and We can create an structure like:
  
  model/spectrum/
     
   - ISpectrum
   - Spectrum
   - ConcensusSpectra 
 
I will create this model in the core, and important good practice should be to create a for each class the 
 corresponding test classes for best practices.

**Comment by ypriverol** [comment]
For the testing of he classes we can use some functions to filter on Spectrums by quality. Specially, it would be interesting to run this to check how many spectrum are god quality and bad quality in terms of peaks intensity, etc. Is just an idea for testing.

**Comment by ruiwanguk** [comment]
I propose we can a set of rules to guide our code ethic:

1. Unit test must be provided for all key components and all algorithm related code.
2. Coding convention following the [Google Java Style Guideline](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html)
3. All code must be documented at all time.

@ypriverol if you agree, I will close this issue and move the results to the wiki.

**Comment by ypriverol** [comment]
Agree
